{% set name = "newmap" %}
{% set version = "0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
- url: https://github.com/hoffmangroup/newmap/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8a6df757a70f0345ad526bbd54b8168d12f646dee5dc8f9697d993667f198a1d
- url: https://github.com/TravisWheelerLab/AvxWindowFmIndex/archive/refs/tags/v1.7.3.tar.gz
  sha256: 3a88368a0988758d17f93bd69aacffbd394c35618a5dc0b9a62c2b626d5202d1
  folder: AvxWindowFmIndex

build:
  number: 0
  skip: True  # [py < 39]
  # Downstream dependencies should expect breaking changes on major version
  run_exports:
    - {{ pin_subpackage('newmap', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
  run:
    - python
    - numpy

test:
    commands:
    - newmap --help
    - newmap index --help
    - newmap search --help
    - newmap track --help
    # Test functionality
    - pushd tests && ./run_all.sh && popd

about:
  home: "https://github.com/hoffmangroup/newmap"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "Tool for creating mappability data for reference sequences."
  doc_url: "https://newmap.readthedocs.io/en/latest"
  dev_url: "https://github.com/hoffmangroup/newmap"

extra:
  skip-lints:
    - uses_vcs_url
