package:
  name: genomedata
  version: "1.4.0"

source:
  fn: genomedata-1.4.0.tar.gz
  url: https://pypi.python.org/packages/8d/ab/60c0ba4affa11f2b2a413aa39956bc79707ef6b6fa9b9712e2d1d412442b/genomedata-1.4.0.tar.gz
  md5: c680b8064df788f3e3476406e0a0d1de
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  skip: True # [not py27]
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - genomedata = genomedata:main
    #
    # Would create an entry point called genomedata that calls genomedata.main()

    - genomedata-info=genomedata._info:main
    - genomedata-query=genomedata._query:main
    - genomedata-histogram=genomedata._histogram:main
    - genomedata-load=genomedata.load_genomedata:main
    - genomedata-load-seq=genomedata._load_seq:main
    - genomedata-load-assembly=genomedata._load_seq:main
    - genomedata-open-data=genomedata._open_data:main
    - genomedata-hardmask=genomedata._hardmask:main
    - genomedata-close-data=genomedata._close_data:main
    - genomedata-report=genomedata._report:main
    - genomedata-erase-data=genomedata._erase_data:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - forked-path
    - pytables >=3.0
    - textinput
    - gcc
    - hdf5 {{ CONDA_HDF5 }}*
    - hgtools

  run:
    - python
    - numpy
    - forked-path
    - pytables >=3.0
    - textinput
    - libgcc
    - hdf5 {{ CONDA_HDF5 }}*
    - hgtools
    - bedtools
    - ucsc-bigwigtobedgraph

test:
  # Python imports
  imports:
    - genomedata

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - genomedata-info --help
    - genomedata-query --help
    - genomedata-histogram --help
    - genomedata-load --help
    - genomedata-load-seq --help
    - genomedata-load-assembly --help
    - genomedata-open-data --help
    - genomedata-hardmask --help
    - genomedata-close-data --help
    - genomedata-report --help
    - genomedata-erase-data --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://genomedata.hoffmanlab.org/
  license: GPL2
  summary: 'tools for accessing large amounts of genomic data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
