{% set version = "1.4.2" %}

package:
  name: genomedata
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/52/e0/c22e9b44a897472cf7c315d41ca50b1454ea7e650cda88326f55682ac328/genomedata-{{ version }}.tar.gz
  sha256: 2d2c47b49fa9b8b32f5b145d87685ca07b958c003a37255a0edc4dafad1fb25e
  
build:
  entry_points:
    - genomedata-info=genomedata._info:main
    - genomedata-query=genomedata._query:main
    - genomedata-histogram=genomedata._histogram:main
    - genomedata-load=genomedata.load_genomedata:main
    - genomedata-load-seq=genomedata._load_seq:main
    - genomedata-load-assembly=genomedata._load_seq:main
    - genomedata-open-data=genomedata._open_data:main
    - genomedata-hardmask=genomedata._hardmask:main
    - genomedata-close-data=genomedata._close_data:main
    - genomedata-report=genomedata._report:main
    - genomedata-erase-data=genomedata._erase_data:main
  number: 0

requirements:
  build:
    - six
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - path.py
    - pytables >=3.4.3
    - textinput
    - hgtools

  run:
    - python
    - pytables >=3.4.3
    - textinput
    - path.py
    - hgtools
    - bedtools
    - six
    - ucsc-bigwigtobedgraph

test:
  imports:
    - genomedata

  commands:
    - genomedata-info --help
    - genomedata-query --help
    - genomedata-histogram --help
    - genomedata-load --help
    - genomedata-load-seq --help
    - genomedata-load-assembly --help
    - genomedata-open-data --help
    - genomedata-hardmask --help
    - genomedata-close-data --help
    - genomedata-report --help
    - genomedata-erase-data --help

about:
  home: http://genomedata.hoffmanlab.org/
  license: GPL2
  summary: 'tools for accessing large amounts of genomic data'

extra:
  identifiers:
    - biotools:genomedata
    - doi:10.1093/bioinformatics/btq164
