{% set name = "genomedata" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06fb344902a1a759a7e894a21484ef2d6e604406ec6b0d127251a0a1081b4862
  
build:
  # Windows is not supported
  skip: True # [win]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - six
    - hgtools
    # Use same HDF5 and zlib libraries as current PyTables
    - pytables >=3.4.3
  run:
    - python
    - six
    - pytables >=3.4.3
    - path.py
    - textinput
    - bedtools
    - ucsc-bigwigtobedgraph

test:
    source_files:
    - test/*.py
    - test/data/*
    commands:
    # Smoke test commands
    - genomedata-info --help
    - genomedata-query --help
    - genomedata-histogram --help
    - genomedata-load --help
    - genomedata-load-seq --help
    - genomedata-load-assembly --help
    - genomedata-open-data --help
    - genomedata-hardmask --help
    - genomedata-close-data --help
    - genomedata-report --help
    - genomedata-erase-data --help
    - genomedata-load-data --help
    # Test functionality
    - test/run_tests.py

about:
  home: http://genomedata.hoffmanlab.org/
  license: GPL2
  summary: 'tools for accessing large amounts of genomic data'

extra:
  identifiers:
    - biotools:genomedata
    - doi:10.1093/bioinformatics/btq164
