{% set name = "segway" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2f2c97e0ff9d064b8271554e60e954764354d04237876766e55e4e484cbb547

build:
  skip: True # [py35]
  number: 0

requirements:
  host:
    - python
    - six
    - hgtools
    - genomedata
    - gmtk
  run:
    - python
    - six
    - genomedata
    - gmtk
    - autolog 
    - optbuild
    - optplus
    - colorbrewer
    - drmaa >=0.4a3
    - ucsc-bedtobigbed

test:
  imports:
    - segway

  commands:
    - segway --help

about:
  home: http://segway.hoffmanlab.org/
  license: GPL2
  summary: 'a tool for easy pattern discovery and identification in functional genomics data.'

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btx603
    - biotools:segway
