package:
  name: segtools
  version: "1.2"

source:
  fn: segtools-1.2.tar.gz
  url: https://files.pythonhosted.org/packages/a6/b3/ad67bbb5d91fd7981f3f9db8d99333473fbfba67ce9f33e12da39b1794de/segtools-1.2.tar.gz
  sha256: 47383e93c2645e6d2e613eb15ccc968fa57fb0502955370b3848e2fb6557a6e8

build:
  number: 0
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - r-base
    - rpy2 >=2.6.0,<2.9
    - numpy
    - gmtk

  run:
    - python
    - numpy
    - r-base
    - rpy2 >=2.6.0,<2.9
    - r-cairo
    - r-latticeextra
    - r-reshape2
    - r-cluster
    - gmtk
    - textinput
    - genomedata #[py2k]
    - graphviz
    - pygraphviz

test:
  imports:
    - segtools

  commands:
    - segtools-gmtk-parameters --help

about:
  home: http://segtools.hoffmanlab.org/
  license: GPL2
  summary: 'a python package for analyzing genomic segmentations'
