package:
  name: segtools
  version: "1.1.13"

source:
  fn: segtools-1.1.13.tar.gz
  url: https://pypi.python.org/packages/25/35/ee812d93d688f664354ed6528a5ade267e86d80c8ea81e16b42c9a386200/segtools-1.1.13.tar.gz
  md5: bae86bef2c86479501bef110c6876f2f

build:
  preserve_egg_dir: True
  skip: True # [not py27]
  entry_points:
    - segtools-aggregation = segtools.aggregation:main
    - segtools-compare = segtools.compare:main
    - segtools-feature-distance = segtools.feature_distance:main
    - segtools-flatten = segtools.flatten:main
    - segtools-gmtk-parameters = segtools.gmtk_parameters:main
    - segtools-html-report = segtools.html:main
    - segtools-length-distribution = segtools.length_distribution:main
    - segtools-nucleotide-frequency = segtools.nucleotide_frequency:main
    - segtools-overlap = segtools.overlap:main
    - segtools-preprocess = segtools.preprocess:main
    - segtools-relabel = segtools.relabel:main
    - segtools-signal-distribution = segtools.signal_distribution:main
    - segtools-transition = segtools.transition:main

requirements:
  build:
    - python
    - setuptools
    - r
    - rpy2 >=2.6.0,<2.9
    - numpy
    - gmtk
    - genomedata

  run:
    - python
    - numpy
    - r
    - rpy2 >=2.6.0,<2.9
    - r-cairo
    - r-latticeextra
    - r-reshape2
    - gmtk
    - genomedata
    - graphviz
    - pygraphviz

test:
  imports:
    - segtools

  commands:
    - segtools-gmtk-parameters --help

about:
  home: http://segtools.hoffmanlab.org/
  license: GPL2
  summary: 'a python package for analyzing genomic segmentations'
